import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

// Read the addresses file generated by the global setup script
const addressesFile = path.join(process.cwd(), './test/script/test-addresses.env');

if (fs.existsSync(addressesFile)) {
  const addressesContent = fs.readFileSync(addressesFile, 'utf-8');
  const addresses = dotenv.parse(addressesContent);
  
  // 1. Point the Oracle Address to the deployed Mock Chronicle contract
  process.env.ONCHAIN_ORACLE_ADDRESS = addresses.MOCK_CHRONICLE_ADDRESS;
  
  // 2. Ensure other mock addresses are set
  process.env.MOCK_CHRONICLE_ADDRESS = addresses.MOCK_CHRONICLE_ADDRESS;
  process.env.MOCK_VAULT_ADDRESS = addresses.MOCK_VAULT_ADDRESS;
  process.env.MOCK_VAULT_AUTH_ADDRESS = addresses.MOCK_VAULT_AUTH_ADDRESS;

  // 3. Force Chain ID to 1 (Local Anvil)
  process.env.CHAIN_ID = '1';

  // 4. FIX: Force optimal bucket difference to 10 to prevent DustyBucket errors in tests
  process.env.OPTIMAL_BUCKET_DIFF = '10';

  // 5. Disable your Fixed Price override
  delete process.env.FIXED_PRICE; 
}
