[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
script = "test/script"
auto_detect_remappings = false
optimizer = true
optimizer_runs = 1
via_ir = true
fs_permissions = [
    { access = "read-write", path = "./test/script/" }
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ajna-core/=lib/4626-ajna-vault/lib/ajna-core/src/",
    "lib/4626-ajna-vault/:lib/ajna-core/=lib/4626-ajna-vault/lib/ajna-core/",
    "lib/4626-ajna-vault/:@openzeppelin/=lib/4626-ajna-vault/lib/ajna-core/lib/openzeppelin-contracts/",
    "lib/Aave-Vault/:@openzeppelin/=lib/Aave-Vault/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/4626-ajna-vault/lib/ajna-core/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/=lib/Aave-Vault/lib/openzeppelin-contracts-upgradeable/contracts/",
    "@prb-math/=lib/4626-ajna-vault/lib/ajna-core/lib/prb-math/",
    "openzeppelin-contracts/=lib/euler-earn/lib/openzeppelin-contracts/contracts/",
    "ethereum-vault-connector/=lib/euler-earn/lib/ethereum-vault-connector/src/",
    "euler-earn/=lib/euler-earn/",
    "Aave-Vault/=lib/Aave-Vault/",
    "@aave-v3-core/=lib/Aave-Vault/lib/aave-v3-core/contracts/",
    "@aave-v3-periphery/=lib/Aave-Vault/lib/aave-v3-periphery/contracts/"
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
