import type { Abi } from 'viem';

export const eulerEarnAbi = [
  // Errors
  { type: 'error', name: 'BadQuery', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'NotCuratorRole', inputs: [] },
  { type: 'error', name: 'NotAllocatorRole', inputs: [] },
  { type: 'error', name: 'NotGuardianRole', inputs: [] },
  { type: 'error', name: 'NotCuratorNorGuardianRole', inputs: [] },
  { type: 'error', name: 'UnauthorizedMarket', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'InconsistentAsset', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'SupplyCapExceeded', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'MaxFeeExceeded', inputs: [] },
  { type: 'error', name: 'AlreadySet', inputs: [] },
  { type: 'error', name: 'AlreadyPending', inputs: [] },
  { type: 'error', name: 'PendingCap', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'PendingRemoval', inputs: [] },
  { type: 'error', name: 'NonZeroCap', inputs: [] },
  { type: 'error', name: 'DuplicateMarket', inputs: [{ name: 'id', type: 'address' }] },
  {
    type: 'error',
    name: 'InvalidMarketRemovalNonZeroCap',
    inputs: [{ name: 'id', type: 'address' }],
  },
  {
    type: 'error',
    name: 'InvalidMarketRemovalNonZeroSupply',
    inputs: [{ name: 'id', type: 'address' }],
  },
  {
    type: 'error',
    name: 'InvalidMarketRemovalTimelockNotElapsed',
    inputs: [{ name: 'id', type: 'address' }],
  },
  { type: 'error', name: 'NoPendingValue', inputs: [] },
  { type: 'error', name: 'NotEnoughLiquidity', inputs: [] },
  { type: 'error', name: 'MarketNotEnabled', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'AboveMaxTimelock', inputs: [] },
  { type: 'error', name: 'BelowMinTimelock', inputs: [] },
  { type: 'error', name: 'TimelockNotElapsed', inputs: [] },
  { type: 'error', name: 'MaxQueueLengthExceeded', inputs: [] },
  { type: 'error', name: 'ZeroFeeRecipient', inputs: [] },
  { type: 'error', name: 'InconsistentReallocation', inputs: [] },
  { type: 'error', name: 'AllCapsReached', inputs: [] },
  { type: 'error', name: 'NotAdminNorVaultOwner', inputs: [] },
  { type: 'error', name: 'IncorrectFee', inputs: [] },
  { type: 'error', name: 'EmptyWithdrawals', inputs: [] },
  { type: 'error', name: 'InconsistentWithdrawals', inputs: [] },
  { type: 'error', name: 'DepositMarketInWithdrawals', inputs: [] },
  { type: 'error', name: 'ZeroShares', inputs: [] },
  { type: 'error', name: 'WithdrawZero', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'MaxSettableFlowCapExceeded', inputs: [] },
  { type: 'error', name: 'FeeTransferFailed', inputs: [{ name: 'feeRecipient', type: 'address' }] },
  { type: 'error', name: 'NotEnoughSupply', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'MaxOutflowExceeded', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'MaxInflowExceeded', inputs: [{ name: 'id', type: 'address' }] },
  { type: 'error', name: 'MaxUint128Exceeded', inputs: [] },
  { type: 'error', name: 'BadAssetReceiver', inputs: [] },

  // ERC-20 events
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      { name: 'spender', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  // ERC-4626 events
  {
    type: 'event',
    name: 'Deposit',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'assets', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdraw',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'assets', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },

  // ERC-20 functions
  {
    type: 'function',
    name: 'name',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },

  // ERC-20Permit functions
  {
    type: 'function',
    name: 'permit',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
      { name: 'v', type: 'uint8' },
      { name: 'r', type: 'bytes32' },
      { name: 's', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'nonces',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'DOMAIN_SEPARATOR',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },

  // ERC-4626 functions
  {
    type: 'function',
    name: 'asset',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'totalAssets',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'convertToShares',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'convertToAssets',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'receiver', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxMint',
    stateMutability: 'view',
    inputs: [{ name: 'receiver', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewMint',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'mint',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxWithdraw',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewWithdraw',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner', type: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxRedeem',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewRedeem',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'redeem',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner', type: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256' }],
  },

  // IOwnable functions
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'transferOwnership',
    stateMutability: 'nonpayable',
    inputs: [{ name: '', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptOwnership',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pendingOwner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },

  // IEulerEarnBase view functions
  {
    type: 'function',
    name: 'permit2Address',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'creator',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'curator',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'isAllocator',
    stateMutability: 'view',
    inputs: [{ name: 'target', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'guardian',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'fee',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint96' }],
  },
  {
    type: 'function',
    name: 'feeRecipient',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'timelock',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'supplyQueue',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'supplyQueueLength',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'withdrawQueue',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'withdrawQueueLength',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxWithdrawFromStrategy',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'expectedSupplyAssets',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'lastTotalAssets',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'lostAssets',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },

  // IEulerEarnBase write functions
  {
    type: 'function',
    name: 'submitTimelock',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newTimelock', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptTimelock',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokePendingTimelock',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitCap',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'id', type: 'address' },
      { name: 'newSupplyCap', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptCap',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokePendingCap',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitMarketRemoval',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokePendingMarketRemoval',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'id', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setName',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newName', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setSymbol',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newSymbol', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitGuardian',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newGuardian', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptGuardian',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokePendingGuardian',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setIsAllocator',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'newAllocator', type: 'address' },
      { name: 'newIsAllocator', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setCurator',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newCurator', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFee',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newFee', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeRecipient',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newFeeRecipient', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setSupplyQueue',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newSupplyQueue', type: 'address[]' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'updateWithdrawQueue',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'indexes', type: 'uint256[]' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reallocate',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'allocations',
        type: 'tuple[]',
        components: [
          { name: 'id', type: 'address' },
          { name: 'assets', type: 'uint256' },
        ],
      },
    ],
    outputs: [],
  },

  // IEulerEarn-specific functions
  {
    type: 'function',
    name: 'EVC',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'config',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'balance', type: 'uint112' },
          { name: 'cap', type: 'uint136' },
          { name: 'enabled', type: 'bool' },
          { name: 'removableAt', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'pendingGuardian',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'value', type: 'address' },
          { name: 'validAt', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'pendingCap',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'value', type: 'uint136' },
          { name: 'validAt', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'pendingTimelock',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'value', type: 'uint136' },
          { name: 'validAt', type: 'uint64' },
        ],
      },
    ],
  },
] as const satisfies Abi;

export type EulerEarnAbi = typeof eulerEarnAbi;
