export const poolInfoUtilsAbi = [
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'borrower_', type: 'address' },
    ],
    name: 'auctionInfo',
    outputs: [
      { name: 'kicker_', type: 'address' },
      { name: 'bondFactor_', type: 'uint256' },
      { name: 'bondSize_', type: 'uint256' },
      { name: 'kickTime_', type: 'uint256' },
      { name: 'referencePrice_', type: 'uint256' },
      { name: 'neutralPrice_', type: 'uint256' },
      { name: 'debtToCollateral_', type: 'uint256' },
      { name: 'head_', type: 'address' },
      { name: 'next_', type: 'address' },
      { name: 'prev_', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'borrower_', type: 'address' },
    ],
    name: 'auctionStatus',
    outputs: [
      { name: 'kickTime_', type: 'uint256' },
      { name: 'collateral_', type: 'uint256' },
      { name: 'debtToCover_', type: 'uint256' },
      { name: 'isCollateralized_', type: 'bool' },
      { name: 'price_', type: 'uint256' },
      { name: 'neutralPrice_', type: 'uint256' },
      { name: 'referencePrice_', type: 'uint256' },
      { name: 'debtToCollateral_', type: 'uint256' },
      { name: 'bondFactor_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'availableQuoteTokenAmount',
    outputs: [{ name: 'amount_', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'borrowFeeRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'borrower_', type: 'address' },
    ],
    name: 'borrowerInfo',
    outputs: [
      { name: 'debt_', type: 'uint256' },
      { name: 'collateral_', type: 'uint256' },
      { name: 't0Np_', type: 'uint256' },
      { name: 'thresholdPrice_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'index_', type: 'uint256' },
    ],
    name: 'bucketInfo',
    outputs: [
      { name: 'price_', type: 'uint256' },
      { name: 'quoteTokens_', type: 'uint256' },
      { name: 'collateral_', type: 'uint256' },
      { name: 'bucketLP_', type: 'uint256' },
      { name: 'scale_', type: 'uint256' },
      { name: 'exchangeRate_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'depositFeeRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'hpb',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'hpbIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'htp',
    outputs: [{ name: 'htp_', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'index_', type: 'uint256' }],
    name: 'indexToPrice',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'lenderInterestMargin',
    outputs: [{ name: 'lenderInterestMargin_', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'lp_', type: 'uint256' },
      { name: 'index_', type: 'uint256' },
    ],
    name: 'lpToCollateral',
    outputs: [{ name: 'collateralAmount_', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'ajnaPool_', type: 'address' },
      { name: 'lp_', type: 'uint256' },
      { name: 'index_', type: 'uint256' },
    ],
    name: 'lpToQuoteTokens',
    outputs: [{ name: 'quoteAmount_', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'lup',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'lupIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'data', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', type: 'bytes[]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'poolLoansInfo',
    outputs: [
      { name: 'poolSize_', type: 'uint256' },
      { name: 'loansCount_', type: 'uint256' },
      { name: 'maxBorrower_', type: 'address' },
      { name: 'pendingInflator_', type: 'uint256' },
      { name: 'pendingInterestFactor_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'poolPricesInfo',
    outputs: [
      { name: 'hpb_', type: 'uint256' },
      { name: 'hpbIndex_', type: 'uint256' },
      { name: 'htp_', type: 'uint256' },
      { name: 'htpIndex_', type: 'uint256' },
      { name: 'lup_', type: 'uint256' },
      { name: 'lupIndex_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'poolReservesInfo',
    outputs: [
      { name: 'reserves_', type: 'uint256' },
      { name: 'claimableReserves_', type: 'uint256' },
      { name: 'claimableReservesRemaining_', type: 'uint256' },
      { name: 'auctionPrice_', type: 'uint256' },
      { name: 'timeRemaining_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'ajnaPool_', type: 'address' }],
    name: 'poolUtilizationInfo',
    outputs: [
      { name: 'poolMinDebtAmount_', type: 'uint256' },
      { name: 'poolCollateralization_', type: 'uint256' },
      { name: 'poolActualUtilization_', type: 'uint256' },
      { name: 'poolTargetUtilization_', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'price_', type: 'uint256' }],
    name: 'priceToIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
] as const;
