export const poolAbi = [
  {
    type: 'function',
    name: 'addQuoteToken',
    inputs: [
      { name: 'amount_', type: 'uint256', internalType: 'uint256' },
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'bucketLP_', type: 'uint256', internalType: 'uint256' },
      { name: 'addedAmount_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approveLPTransferors',
    inputs: [{ name: 'transferors_', type: 'address[]', internalType: 'address[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approvedTransferors',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'auctionInfo',
    inputs: [{ name: 'borrower_', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'kicker_', type: 'address', internalType: 'address' },
      { name: 'bondFactor_', type: 'uint256', internalType: 'uint256' },
      { name: 'bondSize_', type: 'uint256', internalType: 'uint256' },
      { name: 'kickTime_', type: 'uint256', internalType: 'uint256' },
      { name: 'referencePrice_', type: 'uint256', internalType: 'uint256' },
      { name: 'neutralPrice_', type: 'uint256', internalType: 'uint256' },
      { name: 'debtToCollateral_', type: 'uint256', internalType: 'uint256' },
      { name: 'head_', type: 'address', internalType: 'address' },
      { name: 'next_', type: 'address', internalType: 'address' },
      { name: 'prev_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'borrowerInfo',
    inputs: [{ name: 'borrower_', type: 'address', internalType: 'address' }],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bucketExchangeRate',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'exchangeRate_', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bucketInfo',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'burnInfo',
    inputs: [{ name: 'burnEventEpoch_', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'collateralAddress',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'currentBurnEpoch',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'debtInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'decreaseLPAllowance',
    inputs: [
      { name: 'spender_', type: 'address', internalType: 'address' },
      { name: 'indexes_', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'amounts_', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'depositIndex',
    inputs: [{ name: 'debt_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositScale',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositSize',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositUpToIndex',
    inputs: [{ name: 'index_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositUtilization',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'emasInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'increaseLPAllowance',
    inputs: [
      { name: 'spender_', type: 'address', internalType: 'address' },
      { name: 'indexes_', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'amounts_', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'inflatorInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'interestRateInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'kick',
    inputs: [
      { name: 'borrower_', type: 'address', internalType: 'address' },
      { name: 'npLimitIndex_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'kickReserveAuction',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'kickerInfo',
    inputs: [{ name: 'kicker_', type: 'address', internalType: 'address' }],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lenderInfo',
    inputs: [
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
      { name: 'lender_', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'lpBalance_', type: 'uint256', internalType: 'uint256' },
      { name: 'depositTime_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lenderKick',
    inputs: [
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
      { name: 'npLimitIndex_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'loanInfo',
    inputs: [{ name: 'loanId_', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'loansInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpAllowance',
    inputs: [
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
      { name: 'spender_', type: 'address', internalType: 'address' },
      { name: 'owner_', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'allowance_', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'moveQuoteToken',
    inputs: [
      { name: 'maxAmount_', type: 'uint256', internalType: 'uint256' },
      { name: 'fromIndex_', type: 'uint256', internalType: 'uint256' },
      { name: 'toIndex_', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'fromBucketLP_', type: 'uint256', internalType: 'uint256' },
      { name: 'toBucketLP_', type: 'uint256', internalType: 'uint256' },
      { name: 'movedAmount_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pledgedCollateral',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolType',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'quoteTokenAddress',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'quoteTokenScale',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'removeQuoteToken',
    inputs: [
      { name: 'maxAmount_', type: 'uint256', internalType: 'uint256' },
      { name: 'index_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'removedAmount_', type: 'uint256', internalType: 'uint256' },
      { name: 'redeemedLP_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reservesInfo',
    inputs: [],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'revokeLPAllowance',
    inputs: [
      { name: 'spender_', type: 'address', internalType: 'address' },
      { name: 'indexes_', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeLPTransferors',
    inputs: [{ name: 'transferors_', type: 'address[]', internalType: 'address[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stampLoan',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'takeReserves',
    inputs: [{ name: 'maxAmount_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'amount_', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalAuctionsInPool',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalT0Debt',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalT0DebtInAuction',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferLP',
    inputs: [
      { name: 'owner_', type: 'address', internalType: 'address' },
      { name: 'newOwner_', type: 'address', internalType: 'address' },
      { name: 'indexes_', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateInterest',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawBonds',
    inputs: [
      { name: 'recipient_', type: 'address', internalType: 'address' },
      { name: 'maxAmount_', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'withdrawnAmount_', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
] as const;
