import type { Abi } from 'viem';

export const vaultAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_pool', type: 'address' },
      { name: '_sage', type: 'address' },
      { name: '_asset', type: 'address' },
      { name: '_name', type: 'string' },
      { name: '_symbol', type: 'string' },
      { name: '_admin', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', name: 'InvalidQuoteToken', inputs: [] },
  { type: 'error', name: 'ReentrancyLockActive', inputs: [] },
  { type: 'error', name: 'InvalidDeposit', inputs: [] },
  {
    type: 'error',
    name: 'InvalidAssetDecimals',
    inputs: [{ name: 'decimals', type: 'uint8' }],
  },
  {
    type: 'error',
    name: 'DustyBucket',
    inputs: [
      { name: 'pool', type: 'address' },
      { name: 'bucket', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'FundsNotAvailable', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'NotAuthorized', inputs: [] },
  { type: 'error', name: 'VaultUnpaused', inputs: [] },
  { type: 'error', name: 'VaultPaused', inputs: [] },
  { type: 'error', name: 'RemovedCollateralValueNotZero', inputs: [] },

  {
    type: 'event',
    name: 'MoveFromBuffer',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'pool', type: 'address', indexed: true },
      { name: 'bucket', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MoveToBuffer',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'pool', type: 'address', indexed: true },
      { name: 'bucket', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Move',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'pool', type: 'address', indexed: true },
      { name: 'fromBucket', type: 'uint256', indexed: false },
      { name: 'toBucket', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Drain',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'bucket', type: 'uint256', indexed: false },
      { name: 'oldLps', type: 'uint256', indexed: false },
      { name: 'newLps', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetAdmin',
    inputs: [
      { name: 'oldAdmin', type: 'address', indexed: true },
      { name: 'newAdmin', type: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecoverCollateral',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'bucket', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'lps', type: 'uint256', indexed: false },
      { name: 'value', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ReturnQuoteToken',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'bucket', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'lps', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetSwapper',
    inputs: [
      { name: 'oldSwapper', type: 'address', indexed: true },
      { name: 'newSwapper', type: 'address', indexed: true },
    ],
    anonymous: false,
  },
  { type: 'event', name: 'Paused', inputs: [], anonymous: false },
  { type: 'event', name: 'Unpaused', inputs: [], anonymous: false },

  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { name: 'owner', type: 'address', indexed: true },
      { name: 'spender', type: 'address', indexed: true },
      { name: 'value', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Deposit',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'assets', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdraw',
    inputs: [
      { name: 'caller', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'assets', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },

  {
    type: 'function',
    name: 'name',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'drain',
    stateMutability: 'nonpayable',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'pure',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'asset',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'totalAssets',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'convertToShares',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'convertToAssets',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'receiver', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxMint',
    stateMutability: 'view',
    inputs: [{ name: 'receiver', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewMint',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxWithdraw',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewWithdraw',
    stateMutability: 'view',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxRedeem',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewRedeem',
    stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getBuckets',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'pool',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'buffer',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'info',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'bowls',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '_sum', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'pail',
    stateMutability: 'view',
    inputs: [{ name: '_bucket', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'lpToValue',
    stateMutability: 'view',
    inputs: [{ name: '_bucket', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'separateBowls',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: '_quoteTokenValue', type: 'uint256' },
      { name: '_collateralValue', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'lpToValuesSeparately',
    stateMutability: 'view',
    inputs: [{ name: '_bucket', type: 'uint256' }],
    outputs: [
      { name: '_quoteTokenValue', type: 'uint256' },
      { name: '_collateralValue', type: 'uint256' },
      { name: '_price', type: 'uint256' },
      { name: '_vaultLPs', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'WAD',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'POOL',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'INFO',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'BUFFER',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'assetDecimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'LP_DUST',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'buckets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'bucketsIndex',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'bufferLps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'lps',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'bolt',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'admin',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'mint',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner', type: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'redeem',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner', type: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'move',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_fromIndex', type: 'uint256' },
      { name: '_toIndex', type: 'uint256' },
      { name: '_amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'moveFromBuffer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_toIndex', type: 'uint256' },
      { name: '_amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'moveToBuffer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_fromIndex', type: 'uint256' },
      { name: '_amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setAdmin',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_admin', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'recoverCollateral',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_fromIndex', type: 'uint256' },
      { name: '_amt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'returnQuoteToken',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_toIndex', type: 'uint256' },
      { name: '_amt', type: 'uint256' },
    ],
    outputs: [],
  },
] as const satisfies Abi;

export type VaultAbi = typeof vaultAbi;
