export const vaultAuthAbi = [
  {
    inputs: [{ name: '_admin', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    type: 'error',
    name: 'ZeroAddress',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotAuthorized',
    inputs: [],
  },
  {
    type: 'error',
    name: 'BufferRatioTooHigh',
    inputs: [],
  },
  {
    type: 'error',
    name: 'FeeTooHigh',
    inputs: [],
  },
  {
    type: 'event',
    name: 'SetAdmin',
    inputs: [{ name: 'newAdmin', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'SetSwapper',
    inputs: [{ name: 'newSwapper', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'KeeperSet',
    inputs: [
      { name: 'keeper', type: 'address', indexed: true },
      { name: 'isKeeper', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [],
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [],
  },
  {
    type: 'event',
    name: 'DepositCapSet',
    inputs: [{ name: 'newDepositCap', type: 'uint256', indexed: false }],
  },
  {
    type: 'event',
    name: 'BufferRatioSet',
    inputs: [{ name: 'newBufferRatio', type: 'uint256', indexed: false }],
  },
  {
    type: 'event',
    name: 'TollSet',
    inputs: [{ name: 'newToll', type: 'uint256', indexed: false }],
  },
  {
    type: 'event',
    name: 'TaxSet',
    inputs: [{ name: 'newTax', type: 'uint256', indexed: false }],
  },
  {
    type: 'event',
    name: 'MinBucketIndexSet',
    inputs: [{ name: 'newMinBucketIndex', type: 'uint256', indexed: false }],
  },
  {
    inputs: [],
    name: 'admin',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'swapper',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'keepers',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'depositCap',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'bufferRatio',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'toll',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tax',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minBucketIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'isAdmin',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'isSwapper',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'isKeeper',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'isAdminOrKeeper',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'isAdminOrSwapper',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_admin', type: 'address' }],
    name: 'setAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_swapper', type: 'address' }],
    name: 'setSwapper',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_keeper', type: 'address' },
      { name: '_isKeeper', type: 'bool' },
    ],
    name: 'setKeeper',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_depositCap', type: 'uint256' }],
    name: 'setDepositCap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_bufferRatio', type: 'uint256' }],
    name: 'setBufferRatio',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_toll', type: 'uint256' }],
    name: 'setToll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_tax', type: 'uint256' }],
    name: 'setTax',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_minBucketIndex', type: 'uint256' }],
    name: 'setMinBucketIndex',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'retrieveFees',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
